[package]
name = "firefox-control"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
serde_json = "1.0.117"
signal-hook = "0.3.17"

[[bin]]
name = "firefox-control-daemon"

[[bin]]
name = "firefox-cli"
